name: Build Github Packages

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: git fetch --prune --unshallow

      - name: Setup Environments
        id: envs
        run: |
          IPTVCHECKER_LATEST_TAG=${{github.ref_name}}
          DOCKER_IMAGE=${{env.REGISTRY}}/${{ github.repository }}

          echo "RELEASE_VERSION=${GITHUB_REF#refs}"
          TAGS="${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:${IPTVCHECKER_LATEST_TAG}"

          echo "IPTVCHECKER_LATEST_TAG:${IPTVCHECKER_LATEST_TAG}"
          echo ::set-output name=tags::${TAGS}
          mkdir iptv-checker && cp dockerfile iptv-checker/dockerfile

      - name: Checkout iptv-checker-rs
        uses: actions/checkout@v4
        with:
          repository: zhimin-dev/iptv-checker-rs
          path: ./iptv-checker-rs
          token: ${{ secrets.GH_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx Command
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: iptv-checker/dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.envs.outputs.tags }}
